function [C_opt, fval, comp_time] = ...
    fit_competitor_matDepth( ...
    method_id, ...
    objFun, ...
    C0, ...
    M, ...
    maxtime_each, ...
    rand_seed)
% ================================================================
% FIT_COMPETITOR_MATDEPTH
%
% method_id:
%
% 1 = fmincon active-set
% 2 = fmincon interior-point
% 3 = fmincon SQP
% 4 = Manopt Barzilai-Borwein
% 5 = Manopt conjugate-gradient
% 6 = Manopt steepest-descent
% 7 = Manopt trust-region
%
% objFun ALWAYS expects a CORRELATION MATRIX.
%
% fmincon:
%   directly parameterizes a correlation matrix.
%
% Manopt:
%   retains sympositivedefinitefactory(M), as in the
%   previous benchmark, and rescales X -> Corr(X)
%   before objFun is evaluated.
% ================================================================

switch method_id

    % ============================================================
    % fmincon: active-set
    % ============================================================

    case 1

        x0 = ...
            vecFromCorrMatrix(C0);

        lb = -ones(size(x0));

        ub = ones(size(x0));

        obj = @(x) ...
            objFun( ...
            corrMatrixFromVec(x,M));

        options = ...
            optimoptions( ...
            'fmincon', ...
            'Display','iter', ...
            'Algorithm','active-set');

        tic;

        [x_opt,fval] = ...
            fmincon( ...
            obj, ...
            x0, ...
            [],[],[],[], ...
            lb, ...
            ub, ...
            @correlationConstraint, ...
            options);

        comp_time = toc;

        C_opt = ...
            corrMatrixFromVec( ...
            x_opt,M);

    % ============================================================
    % fmincon: interior-point
    % ============================================================

    case 2

        x0 = ...
            vecFromCorrMatrix(C0);

        lb = -ones(size(x0));

        ub = ones(size(x0));

        obj = @(x) ...
            objFun( ...
            corrMatrixFromVec(x,M));

        options = ...
            optimoptions( ...
            'fmincon', ...
            'Display','iter', ...
            'Algorithm','interior-point');

        tic;

        [x_opt,fval] = ...
            fmincon( ...
            obj, ...
            x0, ...
            [],[],[],[], ...
            lb, ...
            ub, ...
            @correlationConstraint, ...
            options);

        comp_time = toc;

        C_opt = ...
            corrMatrixFromVec( ...
            x_opt,M);

    % ============================================================
    % fmincon: SQP
    % ============================================================

    case 3

        x0 = ...
            vecFromCorrMatrix(C0);

        lb = -ones(size(x0));

        ub = ones(size(x0));

        obj = @(x) ...
            objFun( ...
            corrMatrixFromVec(x,M));

        options = ...
            optimoptions( ...
            'fmincon', ...
            'Display','iter', ...
            'Algorithm','sqp');

        tic;

        [x_opt,fval] = ...
            fmincon( ...
            obj, ...
            x0, ...
            [],[],[],[], ...
            lb, ...
            ub, ...
            @correlationConstraint, ...
            options);

        comp_time = toc;

        C_opt = ...
            corrMatrixFromVec( ...
            x_opt,M);

    % ============================================================
    % Manopt: Barzilai-Borwein
    % ============================================================

    case 4

        rng(rand_seed);

        manifold = ...
            sympositivedefinitefactory(M);

        problem.M = manifold;

        % IMPORTANT:
        % X is SPD, not necessarily a correlation matrix.
        % Convert X -> correlation before objective evaluation.

        problem.cost = @(X) ...
            objFun( ...
            spd_to_corr(X));

        options = struct();

        options.maxtime = ...
            maxtime_each;

        tic;

        [Xopt, fval, info] = ...
            barzilaiborwein( ...
            problem, ...
            C0, ...
            options); %#ok<ASGLU>

        comp_time = toc;

        % Convert final SPD result to correlation matrix
        C_opt = ...
            spd_to_corr(Xopt);

    % ============================================================
    % Manopt: conjugate-gradient
    % ============================================================

    case 5

        rng(rand_seed);

        manifold = ...
            sympositivedefinitefactory(M);

        problem.M = manifold;

        problem.cost = @(X) ...
            objFun( ...
            spd_to_corr(X));

        options = struct();

        options.maxtime = ...
            maxtime_each;

        tic;

        [Xopt, fval, info] = ...
            conjugategradient( ...
            problem, ...
            C0, ...
            options); %#ok<ASGLU>

        comp_time = toc;

        C_opt = ...
            spd_to_corr(Xopt);

    % ============================================================
    % Manopt: steepest-descent
    % ============================================================

    case 6

        rng(rand_seed);

        manifold = ...
            sympositivedefinitefactory(M);

        problem.M = manifold;

        problem.cost = @(X) ...
            objFun( ...
            spd_to_corr(X));

        options = struct();

        options.maxtime = ...
            maxtime_each;

        tic;

        [Xopt, fval, info] = ...
            steepestdescent( ...
            problem, ...
            C0, ...
            options); %#ok<ASGLU>

        comp_time = toc;

        C_opt = ...
            spd_to_corr(Xopt);

    % ============================================================
    % Manopt: trust-region
    % ============================================================

    case 7

        rng(rand_seed);

        manifold = ...
            sympositivedefinitefactory(M);

        problem.M = manifold;

        problem.cost = @(X) ...
            objFun( ...
            spd_to_corr(X));

        options = struct();

        options.maxtime = ...
            maxtime_each;

        tic;

        [Xopt, fval, info] = ...
            trustregions( ...
            problem, ...
            C0, ...
            options); %#ok<ASGLU>

        comp_time = toc;

        C_opt = ...
            spd_to_corr(Xopt);

    otherwise

        error( ...
            'Unknown method_id = %d.', ...
            method_id);

end

% ================================================================
% Numerical cleanup
% ================================================================

C_opt = ...
    (C_opt+C_opt')/2;

C_opt(1:M+1:end) = 1;

end